### ISSUE TITLE
heroku build error

### ISSUE THREAD

**Issue by pvguerra** [nobreDaniel/pixelup#12]
ERROR in src/app/podcast/episode-details/episode-details.component.html(2,6): : Property 'domSanitizer' is private and only accessible within class 'EpisodeDetailsComponent'.
       src/app/podcast/episode-details/episode-details.component.html(2,6): : Property 'image_url' does not exist on type 'Object[]'.
       src/app/podcast/episode-details/episode-details.component.html(10,52): : Property 'published_at' does not exist on type 'Object[]'.
       src/app/podcast/episode-details/episode-details.component.html(10,52): : Property 'fullDate' does not exist on type 'EpisodeDetailsComponent'.
       src/app/podcast/episode-details/episode-details.component.html(13,24): : Property 'number' does not exist on type 'Object[]'.
       src/app/podcast/episode-details/episode-details.component.html(13,24): : Property 'title' does not exist on type 'Object[]'.
       src/app/podcast/episode-details/episode-details.component.html(18,15): : Property 'domSanitizer' is private and only accessible within class 'EpisodeDetailsComponent'.
       src/app/podcast/episode-details/episode-details.component.html(18,15): : Property 'id' does not exist on type 'Object[]'.
       src/app/podcast/episode-details/episode-details.component.html(22,17): : Property 'long_description' does not exist on type 'Object[]'.

**Comment by pvguerra** [comment]
Erro depois do pull request #16 

ERROR in : Error: Internal error: unknown identifier [{"filePath":"/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/core/core.d.ts","name":"LOCALE_ID","members":[]},{"filePath":"/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/ngx-swiper-wrapper/dist/ngx-swiper-wrapper.d.ts","name":"SWIPER_CONFIG","members":[]}]
           at Object.importExpr$$1 [as importExpr] (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:24170:27)
           at tokenExpr (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:19863:43)
           at providerDef (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:19789:24)
           at /tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:19959:81
           at Array.map (<anonymous>)
           at NgModuleCompiler.compile (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:19959:48)
           at AotCompiler._compileModule (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:24115:36)
           at /tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:24034:70
           at Array.forEach (<anonymous>)
           at AotCompiler._compileImplFile (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:24034:23)
           at /tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:24024:74
           at Array.map (<anonymous>)
           at AotCompiler.emitAllImpls (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler/bundles/compiler.umd.js:24024:39)
           at AngularCompilerProgram.generateFilesForEmit (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler-cli/src/transformers/program.js:620:46)
           at AngularCompilerProgram._emitRender2 (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler-cli/src/transformers/program.js:266:47)
           at AngularCompilerProgram.emit (/tmp/build_927f9205919d048ef048b06c6ead32a7/node_modules/@angular/compiler-cli/src/transformers/program.js:201:22)

**Comment by pvguerra** [comment]
#17 resolve o swiper, falta locale_id

**Comment by pvguerra** [comment]
depois de #18 ainda apareceu esse erro

ERROR in : Error: Internal error: unknown identifier []
           at Object.importExpr$$1 [as importExpr] (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:24170:27)
           at tokenExpr (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:19863:43)
           at providerDef (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:19789:24)
           at /tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:19959:81
           at Array.map (<anonymous>)
           at NgModuleCompiler.compile (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:19959:48)
           at AotCompiler._compileModule (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:24115:36)
           at /tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:24034:70
           at Array.forEach (<anonymous>)
           at AotCompiler._compileImplFile (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:24034:23)
           at /tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:24024:74
           at Array.map (<anonymous>)
           at AotCompiler.emitAllImpls (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler/bundles/compiler.umd.js:24024:39)
           at AngularCompilerProgram.generateFilesForEmit (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler-cli/src/transformers/program.js:620:46)
           at AngularCompilerProgram._emitRender2 (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler-cli/src/transformers/program.js:266:47)
           at AngularCompilerProgram.emit (/tmp/build_d17ae098e56a7e0e4f4df4a754d058ea/node_modules/@angular/compiler-cli/src/transformers/program.js:201:22)
       
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! pixel-up@0.0.0 postinstall: `ng build --aot --prod`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the pixel-up@0.0.0 postinstall script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.CnSKB/_logs/2019-08-22T14_03_33_753Z-debug.log
-----> Build failed

**Comment by nobreDaniel** [comment]
No app.module.ts a variavel Provider tinha alguns campos com '[ ]' como valor, logo dava erro, eu removi os campos e o build funcionou, creio que não tenha afetado em nada no funcionamento, qualquer coisa a mais só falar
